server:
  port: 8080
spring:
  application:
    name: accounts
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/accountsdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: "prod"
  #----config to activate rabbit mq
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
#----config to activate actuator for all endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
endpoints:
  shutdown:
    enabled: true

build:
  version: "v 1.0"
accounts:
  message: "Default"
  contactDetails:
    name: "Default"
    email: "Default"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  enabled: true
info:
  app:
    name: "accounts"
    description: "Accounts Application"
    version: "1.0.0"
